name: TestRelease

on:
  push:
    branches: [fix-ci]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # we need all commit history so we can merge master into not-develop at the end
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          # use node 14 until we can evaluate using npm 7+ and lock file version 2
          node-version: 14

      - name: Import Robot GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.TRUFBOT_GPG_SECRET_KEY }}
          passphrase: ${{ secrets.TRUFBOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Test pushing to not-develop
        run: |
          touch file.txt
          git add .
          git commit -m "test commit"
          git push origin fix-ci
          git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules origin not-develop
          git checkout not-develop
          git merge origin/fix-ci
          git push origin not-develop
